steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  dir: 'food-dash-server'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy --promote --stop-previous-version']
timeout: '1600s'
