# Example workflow
name: Format

on:
  pull_request:

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # v2 minimum required- name: Google Java Format
      - uses: axel-op/googlejavaformat-action@3.5.0
        with:
          args: "-n --set-exit-if-changed"
